Readme.md
build/build.cake
src/Uno.Wasm.Bootstrap/ShellTask.Linker.cs
src/Uno.Wasm.Bootstrap/ShellTask.cs
src/Uno.Wasm.Bootstrap/Uno.Wasm.Bootstrap.csproj
src/Uno.Wasm.Bootstrap/build/Uno.Wasm.Bootstrap.targets

- SDK Uri path override
- Index.html content override
- Move linker step in its own partial class

Add customization options:

---

src/Directory.Build.props
src/Uno.Wasm.Bootstrap/ShellTask.Linker.cs
src/Uno.Wasm.Bootstrap/ShellTask.cs

- Improve "missing an entry point" message to include possible resolution 
- Fixed `ReferencePath` property may be null
- Added SourceLink support

Quality of life updates

---

.gitmodules
Readme.md
src/Uno.Wasm.Bootstrap/Constants.cs
src/Uno.Wasm.Bootstrap/ShellTask.cs
src/Uno.Wasm.Bootstrap/UnoInstallSDKTask.cs
src/Uno.Wasm.Bootstrap/build/Uno.Wasm.Bootstrap.targets

Removes the unused git submodule.
Fixes #30

Update to latest mono-wasm sdk

---

src/Uno.Wasm.Bootstrap/Constants.cs

Fixes https://github.com/mono/mono/pull/12033

Update mono-wasm sdk

---

Readme.md
src/Uno.Wasm.AotTests/Uno.Wasm.AotTests.csproj
src/Uno.Wasm.Bootstrap/ShellTask.cs
src/Uno.Wasm.Sample/Uno.Wasm.Sample.csproj
src/Uno.Wasm.Tests.Empty/Uno.Wasm.Test.Empty.csproj

- Updates the documentation
- Adjust for packager parameters
Fixes https://github.com/nventive/Uno/issues/441

Misc Updates

---

src/Uno.Wasm.AotTests/Uno.Wasm.AotTests.csproj
src/Uno.Wasm.Bootstrap/ShellTask.cs

Disable mono debug in release for AOT sample

Fix WebAssembly.Bindings linking, disable Mono debug

---

src/Uno.Wasm.Bootstrap/build/packager.cs

Fixes missing "_setThrew is not defined" after emscripten update

Update to the latest packager

---

src/Uno.Wasm.Bootstrap/ShellTask.cs

This will force the worker to refresh and rebuild the cache

Touch the service worker file on build

---

.vsts-ci.yml
src/Uno.Wasm.Bootstrap/ShellTask.cs

The wast file was not properly deleted

Fix invalid dist cleanup

---

src/Uno.Wasm.Bootstrap.sln
src/Uno.Wasm.Bootstrap/WasmScripts/uno-bootstrap.js
src/Uno.Wasm.Tests.Electron/Program.cs
src/Uno.Wasm.Tests.Electron/Uno.Wasm.Tests.Electron.csproj
src/Uno.Wasm.Tests.Electron/WasmScripts/test.js
src/Uno.Wasm.Tests.Electron/wwwroot/electron-main.js
src/Uno.Wasm.Tests.Electron/wwwroot/package.json

- Added test project for electron validation
- Fixed wasm module instanciation from local files
Related: https://github.com/nventive/Uno/issues/624

Initial support for Electron

---

src/Uno.Wasm.Bootstrap/WasmScripts/uno-bootstrap.js

- Fixes chrome invalid assembly fetching

Use default fetch in debug

---

src/Uno.Wasm.Bootstrap/Constants.cs
src/Uno.Wasm.Bootstrap/build/packager.cs
src/Uno.Wasm.MixedModeRoslynSample/Uno.Wasm.MixedModeRoslynSample.csproj

Mono commit: d44e45c32ec1315f5ab97b2e2ec5104ccad6e868

Update mono master

---

Readme.md

Fix broken link in Linker configuration section

[doc] - Fix broken link in Linker configuration section

---

src/Uno.Wasm.Bootstrap/Constants.cs
src/Uno.Wasm.Bootstrap/ShellTask.cs
src/Uno.Wasm.Bootstrap/build/packager.cs

mono f5cfc67c8edc8a3172d146b84c6dcb3a6414c216

Update to latest mono master, fix memory override

---

src/Uno.Wasm.Bootstrap/build/packager.cs

Disables dynamic export to JS methods

Update to use main_module=2 feature

---

Readme.md

See
https://github.com/unoplatform/uno/issues/1764
https://github.com/unoplatform/uno/pull/1805
Related #120

Updated csproj constants config

---

.vsts-ci.yml
build/build.cake
src/Uno.Wasm.Bootstrap/Constants.cs

Update to emscripten 1.39.3

---

src/Uno.Wasm.Bootstrap/ShellTask.cs
src/Uno.Wasm.Sample/AdditionalContent/SomeContent01.txt
src/Uno.Wasm.Sample/AdditionalContent/SomeContent02.txt
src/Uno.Wasm.Sample/Program.cs
src/Uno.Wasm.Sample/Uno.Wasm.Sample.csproj

Align mixed path separators

---

.vsts-ci.yml
doc/release-procedure.md
gitversion.yml
src/Uno.Wasm.Bootstrap/ShellTask.cs
src/Uno.Wasm.Sample/Uno.Wasm.Sample.csproj

Fix content copy from linked item

---

.vsts-ci.yml
doc/release-procedure.md
gitversion.yml
src/Uno.Wasm.Bootstrap/ShellTask.cs
src/Uno.Wasm.Bootstrap/Templates/index.html
src/Uno.Wasm.Sample/Uno.Wasm.Sample.csproj

- Fix content copy from linked item
- Added ./ to generated hrefs

Backport fixes

---

gitversion.yml
src/Uno.Wasm.Bootstrap/ShellTask.cs
src/Uno.Wasm.Bootstrap/WasmScripts/service-worker.js
src/Uno.Wasm.Bootstrap/WasmScripts/uno-bootstrap.js

Update PWA caching

---

.vsts-ci.yml
src/Uno.Wasm.Bootstrap/Constants.cs

Emscripten update for https://github.com/emscripten-core/emscripten/issues/9950

Bump mono and emscripten 1.39.7

---

src/Uno.Wasm.Bootstrap/Constants.cs
src/Uno.Wasm.Bootstrap/Packager/packager.cs
src/Uno.Wasm.Bootstrap/ShellTask.cs

Update to mono https://github.com/mono/mono/commits/91e026de9dbe4c00d8563c3270186ad682abf69b
Fixes https://github.com/unoplatform/uno/issues/2696

Update to mono latest

---

src/Uno.Wasm.Bootstrap/ShellTask.cs

Recent WSL builds enforce proper quote escaping, this PR adjusts for that.

Adjust for WSL breaking change

---

src/Uno.Wasm.Bootstrap/ShellTask.cs

Fixes https://github.com/unoplatform/uno/issues/3121

fix(linux): Force load of colocated bootstrapper tooling assemblies

---

src/Uno.Wasm.Bootstrap/Constants.cs

https://github.com/unoplatform/Uno.Wasm.MonoRuntime/commit/b4b8dac81cd9a1efe063426a3e20d4e35236e6fa

chore: Update to mono latest

---

Readme.md
src/Uno.Wasm.Bootstrap/ShellTask.cs
src/Uno.Wasm.Bootstrap/WasmScripts/uno-bootstrap.js
src/Uno.Wasm.Sample/WasmScripts/AppManifest.js

Closes https://github.com/unoplatform/Uno.Wasm.Bootstrap/pull/132, thanks @bradtwurst for the initial work !
Closes https://github.com/unoplatform/uno/issues/2254, Closes https://github.com/unoplatform/uno/issues/2848

fix: Adjust Splash Screen customization configuration

---

src/Uno.Wasm.Bootstrap/ShellTask.cs
src/Uno.Wasm.Sample/Program.cs
src/Uno.Wasm.Sample/Uno.Wasm.Sample.csproj

Fixes https://github.com/unoplatform/Uno.Wasm.Bootstrap/issues/227
Fixes https://github.com/unoplatform/uno/issues/2518

fix: Fix invalid use of reference assemblies when actual assembly is present

---

src/Uno.Wasm.Bootstrap/build/scripts/emscripten-setup.sh

This avoids transient issues as the latest emsdk updates.

fix: Pin emsdk version to the supported emscripten version

---

src/Uno.Wasm.Bootstrap/ShellTask.cs

fix: Build full BaseIntermediateOutputPath

---

src/Uno.Wasm.Bootstrap/Constants.cs

Revert mono until https://github.com/mono/mono/issues/20256 is fixed

fix(reg): Revert mono for Assembly.Load issue

---

.gitpod.yml

fix: Upgrade gitpod base image

---

src/Uno.Wasm.Bootstrap/build/Uno.Wasm.Bootstrap.targets
src/Uno.Wasm.SampleNet5/Program.cs
src/Uno.Wasm.SampleNet5/Uno.Wasm.SampleNet5.csproj

fix: Restore compatibility with `net5` and `net5.0` Target Frameworks

---

Readme.md
src/Uno.Wasm.Bootstrap/ShellTask.cs
src/Uno.Wasm.StaticLinking.Shared/Program.cs

Closes https://github.com/unoplatform/Uno.Wasm.Bootstrap/pull/263

feat: Add support for __Native dll import

---

Readme.md

docs: Update AOT requirements

---

src/Uno.Wasm.Bootstrap/Constants.cs

feat: Update to dotnet/runtime@dec3fff

---

Readme.md

closes https://github.com/unoplatform/Uno.Wasm.Bootstrap/issues/320

docs: Add AMD enabled libraries usage

---

src/Uno.Wasm.Bootstrap/ShellTask.cs

This changes allows for the "start with debugger" command in VS to work even when running in release mode.

fix(debugging): Publish debugger files in all modes

---

src/Uno.Wasm.Bootstrap/Constants.cs

chore: Update to latest dotnet/runtime

---

src/Uno.Wasm.Bootstrap/ShellTask.cs

Closes https://github.com/unoplatform/Uno.Wasm.Bootstrap/issues/329

Misc fixes

---

src/Uno.Wasm.Bootstrap/ShellTask.cs

fix: Use AOT Profile property only in Mixed mode

---

Readme.md

Fix misspelling

---

src/Uno.Wasm.Packager/packager.cs

Addresses https://github.com/dotnet/runtime/issues/50757

Performance and build improvements

---

src/Uno.Wasm.Bootstrap/Constants.cs

Fixes interpreter memory corruption

chore: Update to runtime latest

---

.vsts-ci-linux.yml
.vsts-ci-macos.yml
.vsts-ci-windows-tests.yml
.vsts-ci.yml
src/Uno.Wasm.Bootstrap/Constants.cs

closes https://github.com/unoplatform/Uno.Wasm.Bootstrap/issues/422

fix: Adjust for missing IDBFS in interpreter mode

---

Readme.md
src/Uno.Wasm.Bootstrap/WasmScripts/uno-bootstrap.js
src/Uno.Wasm.Profiler/LogProfilerSupport.cs
src/Uno.Wasm.SampleNet6.LogProfiler/Uno.Wasm.SampleNet6.LogProfiler.csproj

- Moves the file materialization to the javascript side in order to avoid managed memory changes, and avoid memory limits.
- Automatic profile flushing every 5 seconds is also added.

fix: Improve WebAssembly heap consumption

---

src/Uno.Wasm.Bootstrap/WasmCSS/uno-bootstrap.css
src/Uno.Wasm.Bootstrap/WasmScripts/uno-bootstrap.js
src/Uno.Wasm.Sample/WasmScripts/AppManifest.js

Support for theme-aware splash screens!

feat: Theme-aware splash screen

---

src/Uno.Wasm.Bootstrap/ShellTask.cs
src/Uno.Wasm.Static Linking/Uno.Wasm.StaticLinking.csproj

It is not supported by the .NET runtime yet.

ci: Disable FullAOT mode

---

doc/features-linker-opts.md

What kind of change does this PR introduce?
- Bugfix (incorrect link)
"Use the Templates/index.html file as an example." has an incorrect relative path
the path is correct now
Please check if your PR fulfills the following requirements:
Internal Issue (If applicable):

fix: incorrect relative path in features-linker-opts

---

doc/features-linker-opts.md

What kind of change does this PR introduce?
- Bugfix (incorrect link)
"When building an application, place the following file in the wwwroot" 
and
"Templates/index.html when using the bootstrapper 4.x builds." 
have incorrect links
the links are correct now
Please check if your PR fulfills the following requirements:
Internal Issue (If applicable):

fix: incorrect links in features-linker-opts

---

src/Uno.Wasm.Bootstrap/build/Uno.Wasm.Bootstrap.targets
src/Uno.Wasm.Sample/sample.common.props

Publish is never executed in below net6, causing the dist folder to never be created.

fix: Adjust for net5 targets

---

src/Uno.Wasm.Bootstrap/ShellTask.cs
src/Uno.Wasm.Packager/packager.cs

This change avoids long command line errors on windows.

ci: Adjust paths for emcc

---

src/Uno.Wasm.Bootstrap/ShellTask.AOTProfile.cs

It is causing https://github.com/dotnet/runtime/issues/77122

fix(pgaot): Remove workaround for mono/mono/issues/19824

---

Readme.md

cI: Adjust major version

---

src/Uno.Wasm.Bootstrap.Cli/Server/Startup.cs

Always use response compression

---

src/Uno.Wasm.Bootstrap.DevServer/build/Uno.Wasm.Bootstrap.DevServer.targets

fix: Adjust devserver for absolute OutputPath override

---

src/Uno.Wasm.Bootstrap/ShellTask.cs
src/Uno.Wasm.Bootstrap/WasmScripts/service-worker.js

Fixes https://github.com/unoplatform/Uno.Wasm.Bootstrap/issues/659

Adjust service worker installation

---

src/Uno.Wasm.Bootstrap/build/scripts/emscripten-setup.cmd

closes https://github.com/unoplatform/Uno.Wasm.Bootstrap/issues/658

fix: Ensure build failure on emscripten install failure on Windows

---

doc/linker-configuration.md
src/Uno.Wasm.Bootstrap/ShellTask.cs
src/Uno.Wasm.Packager/packager.cs
src/Uno.Wasm.Sample/Program.cs
src/Uno.Wasm.Sample/sample.common.props
src/Uno.Wasm.StaticLinking.Aot.UITests/app.js
src/Uno.Wasm.StaticLinking.Aot.UITests/app.ts
src/Uno.Wasm.StaticLinking.Shared/Common.props
src/Uno.Wasm.StaticLinking.Shared/Program.cs
src/Uno.Wasm.StaticLinking.Shared/Validations.props

closes https://github.com/unoplatform/uno/issues/11043

feat(localization): Add support satellite resource assemblies publishing

---

.vsts-ci-linux.yml
.vsts-ci-wsl-tests.yml
build/scripts/run-tests-csp.sh
doc/features-interop.md
doc/features-profiling.md
doc/features-security.md
doc/runtime-execution-modes.md
doc/toc.yml
src/Uno.Wasm.AotProfiler/Uno.Wasm.AotProfiler.csproj
src/Uno.Wasm.Bootstrap/ShellTask.cs
src/Uno.Wasm.Bootstrap/Uno.Wasm.Bootstrap.csproj
src/Uno.Wasm.Bootstrap/build/Uno.Wasm.Bootstrap.targets
src/Uno.Wasm.Bootstrap/ts/Uno/WebAssembly/AotProfilerSupport.ts
src/Uno.Wasm.Bootstrap/ts/Uno/WebAssembly/Bootstrapper.ts
src/Uno.Wasm.Bootstrap/ts/Uno/WebAssembly/HotReloadSupport.ts
src/Uno.Wasm.Bootstrap/ts/Uno/WebAssembly/LogProfilerSupport.ts
src/Uno.Wasm.LogProfiler/LogProfilerSupport.cs
src/Uno.Wasm.LogProfiler/Uno.Wasm.LogProfiler.csproj
src/Uno.Wasm.MetadataUpdater/Uno.Wasm.MetadataUpdater.csproj
src/Uno.Wasm.MetadataUpdater/WebAssemblyHotReload.cs
src/Uno.Wasm.Sample/Program.cs
src/Uno.Wasm.Sample/WasmScripts/test.js
src/Uno.Wasm.StaticLinking.Shared/Program.cs
src/Uno.Wasm.StaticLinking.Shared/WasmScripts/test.js
src/Uno.Wasm.TimezoneData/TimezoneHelper.cs
src/Uno.Wasm.TimezoneData/Uno.Wasm.TimezoneData.csproj

Close https://github.com/unoplatform/Uno.Wasm.Bootstrap/issues/688

feat: Adjust support for CSP

---

.vsts-ci-windows-tests.yml
doc/features-obfsucation.md
src/Uno.Wasm.Bootstrap.Cli/Server/Startup.cs
src/Uno.Wasm.Bootstrap/FileNameObfuscationMode.cs
src/Uno.Wasm.Bootstrap/ShellTask.cs
src/Uno.Wasm.Bootstrap/build/Uno.Wasm.Bootstrap.targets
src/Uno.Wasm.Bootstrap/ts/Uno/WebAssembly/Bootstrapper.ts
src/Uno.Wasm.Bootstrap/ts/Uno/WebAssembly/UnoConfig.ts
src/Uno.Wasm.SampleNet7/web.config
src/Uno.Wasm.SampleNet7/wwwroot/web.config

feat(obfuscation): Adds support for extension-less assembly URIs

---

src/Uno.Wasm.Bootstrap/WasmCSS/uno-bootstrap.css
src/Uno.Wasm.Bootstrap/ts/Uno/WebAssembly/Bootstrapper.ts

Closes #693, part of https://github.com/unoplatform/uno/issues/10178

Themeable accent color, Persistent splashscreen background

---

src/Uno.Wasm.VersionChecker/UnoVersionExtractor.cs

When non-dll files are published on the server (.pdb, for example), the previous version of uno-wasm-version were crashing. This new version now handle those cases.
Also handle 404 from server.

fix(exception): Fixed support when other files are published

---

src/Uno.Wasm.Bootstrap/WasmCSS/uno-bootstrap.css

Part of https://github.com/unoplatform/uno/issues/11783

fix: Avoid Microsoft Edge visual search popup

---

src/Uno.Wasm.Bootstrap/ShellTask.cs
src/Uno.Wasm.Packager/packager.cs

Include workaround for https://github.com/dotnet/runtime/issues/90745

fix: Add workaround for dotnet/runtime 90745

---

src/Uno.Wasm.Bootstrap/ShellTask.cs
src/Uno.Wasm.Packager/packager.cs

Related to https://github.com/dotnet/runtime/issues/90745

fix: Disable unused attributes trimming

---

src/Uno.Wasm.Bootstrap/ShellTask.cs
src/Uno.Wasm.StaticLinking.Shared/Common.props
src/Uno.Wasm.StaticLinking.Shared/Validations.props

fixes https://github.com/unoplatform/Uno.Wasm.Bootstrap/issues/785

fix: Ensure compression is enabled with nodots obfuscation

---

src/Uno.Wasm.MetadataUpdater/Uno.Wasm.MetadataUpdater.csproj

fixes https://github.com/unoplatform/Uno.Wasm.Bootstrap/issues/780

fix: Build hotreload helper binary for net8

---

.vsts-ci-windows-tests.yml
src/Uno.Wasm.Bootstrap/build/Uno.Wasm.Bootstrap.targets

fixes https://github.com/unoplatform/Uno.Wasm.Bootstrap/issues/819

fix: Restore clean target

---

src/Uno.Wasm.Bootstrap/build/Uno.Wasm.Bootstrap.targets

Related to https://github.com/unoplatform/uno/issues/15560

fix: Ensure that Microsoft.NET.ILLink.Tasks is included in 8.0.200 and later

---

doc/features-additional-files.md

doc: Correct small typo

---

src/Uno.Wasm.Bootstrap/ShellTask.cs

Related to https://github.com/unoplatform/uno.resizetizer/issues/288

fix: Correctly emit PWA manifest path

---

Readme.md

mention .NET 8, correct spelling of JavaScript

Improve Readme.md

---

doc/debugger-support.md
doc/features-interop.md
doc/runtime-execution-modes.md

https://github.com/unoplatform/private/issues/504

docs: Fix Broken Links

---

src/Uno.Wasm.Bootstrap/ShellTask.cs

fix: Adjust deprecated meta tag

---

.github/workflows/ci.yml

ci: Update upload-artifact to v4

---

src/Uno.Wasm.Bootstrap/GenerateUnoAssetsManifestTask.cs

Restores compatibility with net8

fix: Remove leading / in uno-assets.txt

---

src/Uno.Wasm.Bootstrap/build/Uno.Wasm.Bootstrap.targets

Add a workaround for https://github.com/dotnet/runtime/issues/108972

fix: Adjust emscripten version

---

.vsts-ci.yml
src/Uno.Wasm.Bootstrap/Constants.cs

https://github.com/dotnet/runtime/issues/111281

chore: Update runtime to include Wasm+AOT fix

---

src/Uno.Wasm.Bootstrap/ts/Uno/WebAssembly/HotReloadSupport.ts

fixes https://github.com/unoplatform/private/issues/597

fix: Adjust HR for 17.12.4 and later

---

doc/features-environment-variables.md
src/Uno.Wasm.Bootstrap/Embedded/service-worker.js
src/Uno.Wasm.Bootstrap/ShellTask.cs

Improve error handling and caching mechanisms in the service worker to ensure better resilience and performance during network failures. Implement centralized error logging and cache cleanup to manage storage effectively.
Fixes #956

Enhance service worker error handling and caching logic

---

doc/runtime-execution-modes.md

enhance the documentation for https://github.com/unoplatform/uno/issues/20956#issuecomment-3059075832

docs: adjust profile location for uno.sdk

---

.github/workflows/ci.yml

Adjust build for net10 nbgv run

ci: adjust build

---

build/ci/stage-build-windows-tests.yml
doc/using-the-bootstrapper.md
src/Uno.Wasm.Bootstrap/build/Uno.Wasm.Bootstrap.targets

**GitHub Issue:** closes https://github.com/unoplatform/uno/issues/20664

fix: Raise an error when wasm-tools are missing
