Readme.md
src/Uno.Wasm.Bootstrap/ShellTask.cs
src/Uno.Wasm.Bootstrap/WasmScripts/uno-bootstrap.js
src/Uno.Wasm.Bootstrap/build/Uno.Wasm.Bootstrap.targets

Renamed MonoRuntimeDebugLogging to MonoRuntimeDebuggerEnabled, allow for the debugger to be disabled.

Make the debugger features configurable using RuntimeDebuggerEnabled

---

Readme.md
src/Uno.Wasm.Bootstrap/ShellTask.cs
src/Uno.Wasm.Bootstrap/Templates/Index.html
src/Uno.Wasm.Bootstrap/WasmScripts/uno-bootstrap.js

Generate the managed dist path using hash to ease the cache-ability of the managed folder, and rely on the browser's caching mechanism, instead of implemented an emscripten based storage.

Improve cache-ability of the managed folder

---

src/Uno.Wasm.Bootstrap/ShellTask.Linker.cs
src/Uno.Wasm.Bootstrap/WasmScripts/uno-bootstrap.js
src/Uno.Wasm.Bootstrap/build/Uno.Wasm.Bootstrap.targets
src/Uno.Wasm.Sample/Program.cs

This change renames dll/exe files to clrdll/clrexe files on the wire, and renames them to the original name when stored in the wasm module's file system.
Fixes #9

Avoid dll/exe filtering from antivirus software

---

Readme.md
src/Uno.Wasm.Bootstrap/ShellTask.Linker.cs
src/Uno.Wasm.Bootstrap/ShellTask.cs
src/Uno.Wasm.Bootstrap/Templates/Index.html
src/Uno.Wasm.Bootstrap/Uno.Wasm.Bootstrap.csproj
src/Uno.Wasm.Bootstrap/WasmScripts/uno-bootstrap.js

This adjustment is present to workaround an incorrect classification of dll files by "Symantec Endpoint Protection".
See #10 additional details.

Remove unused exe support, rename clrdll to clr extension

---

src/Uno.Wasm.Bootstrap/build/Uno.Wasm.Bootstrap.targets

This fixes an issue where pdb files were loaded as part of the ReferenceCopyLocalPath items:
```
2>packages\uno.wasm.bootstrap\1.0.0-dev.34\build\Uno.Wasm.Bootstrap.targets(25,3): error : AggregateException: One or more errors occurred.
2>packages\uno.wasm.bootstrap\1.0.0-dev.34\build\Uno.Wasm.Bootstrap.targets(25,3): error : BadImageFormatException: Format of the executable (.exe) or library (.dll) is invalid.
```

Adjust for PDB files in ReferenceCopyLocalPaths

---

src/Uno.Wasm.Bootstrap/ShellTask.Linker.cs
src/Uno.Wasm.Bootstrap/ShellTask.cs

Allows for nunit to work from the nuget package instead of the mono-provided version

Ignore NuGet package-provided bcl references

---

src/Uno.Wasm.Bootstrap/ShellTask.Linker.cs
src/Uno.Wasm.Bootstrap/ShellTask.cs

Removing the parallel copy is required as cecil does not behave properly in a multi-threaded context.

Adjust for nunitlite support, parallel extraction issues

---

src/Uno.Wasm.Bootstrap/Uno.Wasm.Bootstrap.csproj

Fixes #42 
The nuget files in the resulting layout was incorrect, breaking the targets import and the linker.

Adjust invalid nuget layout

---

src/Uno.Wasm.Bootstrap/WasmCSS/uno-bootstrap.css

This change is meant to be neutral, until configurability of the loading screen is added (current behavior with UnoAppManifest relies on Uno.UI being present, which is not always the case).

Update the default background color to match default UWP

---

Readme.md
src/Uno.Wasm.Bootstrap/ShellTask.cs
src/Uno.Wasm.Bootstrap/Templates/index.html
src/Uno.Wasm.Bootstrap/Uno.Wasm.Bootstrap.csproj
src/Uno.Wasm.Bootstrap/build/Uno.Wasm.Bootstrap.targets

The `WashShellGeneratePrefetchHeaders` controls the generation of `<link rel="prefetch" />` nodes in the index.html header. 
It is enabled by default and allows for the browser to efficiently fetch the applications webassembly and .NET assemblies files, while the JavaScript and WebAssembly runtimes are  being initialized. 
This prefetching feature is particularly useful if the http server supports HTTP/2.0.

Add support for index.html Content prefetching

---

src/Uno.Wasm.Bootstrap/build/packager.cs

Added to bypass :
```
﻿Error #1 "Unable to grow wasm table. Use a higher value for RESERVED_FUNCTION_POINTERS or set ALLOW_TABLE_GROWTH." executing javascript: "CalcManager.registerCallbacks()"
```

Adjust Wasm table growth

---

src/Uno.Wasm.Bootstrap/build/packager.cs

This update is similar to https://github.com/mono/mono/pull/14873, which avoids the inclusion of `dlmalloc` which seems to have stability issues.

Adjust the emscripten libraries for release dynamic config

---

src/Uno.Wasm.Bootstrap/ShellTask.cs

The generated `index.html` only referred absolute paths. This prevented the application to be placed anywhere but at the root of the website. 
Adding `./` to those paths allows more flexibility with the location of the application.

Added ./ to generated hrefs

---

src/Uno.Wasm.Bootstrap/ShellTask.cs
src/Uno.Wasm.Bootstrap/WasmScripts/service-worker.js
src/Uno.Wasm.Bootstrap/WasmScripts/uno-bootstrap.js

- Use fetch then cache strategy
- Use literal cache version to avoid using already cached version even if the service got updated

Update service worker cache strategy

---

src/Uno.Wasm.Bootstrap/Constants.cs

Avoids the direct dependency on mono-jenkins.

Use stable URI for runtime packages

---

src/Uno.Wasm.Bootstrap/Extensions/LongPathHelper.cs
src/Uno.Wasm.Bootstrap/ShellTask.cs
src/Uno.Wasm.Bootstrap/Uno.Wasm.Bootstrap.csproj

When using the VS 2019 Azure WebApp publication, long path support seems to be disabled by the hosting msbuild executable.
This PR disables long path generation if it is not supported by the current process.
This PR fixes https://github.com/unoplatform/uno/issues/2463.

Add azure publish long path error fallback

---

Readme.md
src/LongPathTest/Uno.Wasm.LongPath.csproj
src/Uno.Wasm.AotTests/Uno.Wasm.AotTests.csproj
src/Uno.Wasm.Bootstrap.Cli/Uno.Wasm.Bootstrap.Cli.csproj
src/Uno.Wasm.Bootstrap.DevServer/Uno.Wasm.Bootstrap.DevServer.csproj
src/Uno.Wasm.Bootstrap.DevServer/build/Uno.Wasm.Bootstrap.DevServer.targets
src/Uno.Wasm.Bootstrap.sln
src/Uno.Wasm.Bootstrap/ShellTask.cs
src/Uno.Wasm.Bootstrap/build/Uno.Wasm.Bootstrap.targets
src/Uno.Wasm.DynamicLinking/Uno.Wasm.DynamicLinking.csproj
src/Uno.Wasm.MixedModeRoslynSample/Uno.Wasm.MixedModeRoslynSample.csproj
src/Uno.Wasm.MixedModeSample/Uno.Wasm.MixedModeSample.csproj
src/Uno.Wasm.Node.Sample/Uno.Wasm.Node.Sample.csproj
src/Uno.Wasm.Sample/Uno.Wasm.Sample.csproj
src/Uno.Wasm.Tests.Electron/Uno.Wasm.Tests.Electron.csproj
src/Uno.Wasm.Tests.Empty/Uno.Wasm.Test.Empty.csproj
src/Uno.Wasm.Tests.TypeScript/Uno.Wasm.Tests.TypeScript.csproj
src/Uno.Wasm.Threads/Uno.Wasm.Threads.csproj
src/Uno.WasmSample WithSpace/Uno.WasmSample.WithSpace.csproj

BREAKING CHANGE: The `Uno.Wasm.Bootstrap.Cli` package is now deprecated and needs to be replaced with `Uno.Wasm.Bootstrap.DevServer` see the documentation for more details.
This change fixes #186, as there is no dotnet-tool to run anymore.

feat: Add Uno.Wasm.Bootstrap.DevServer package

---

.vsts-ci-linux.yml
src/Uno.Wasm.Bootstrap/build/Uno.Wasm.Bootstrap.targets

Fixes https://github.com/unoplatform/uno/issues/2974

fix: Fail the build when a project uses the deprecated CLI package

---

src/Uno.Wasm.Bootstrap/Constants.cs
src/Uno.Wasm.Bootstrap/ShellTask.cs

Uses mono build from https://github.com/unoplatform/Uno.Wasm.MonoRuntime/commit/b4594cefdbb3c36b8b6957eaa30f7e06b94a7a3c
Fixes https://github.com/unoplatform/uno/issues/1451

feat: Update to mono, enable IDBFS by default for interpreter builds

---

src/Uno.Wasm.Bootstrap/Constants.cs

Mono base SHA1: 049de7513a894cae5581c35f3ee0b40f9f2d5f1a
Build https://github.com/unoplatform/Uno.Wasm.MonoRuntime/commit/d43e1064b486c1fb11b4cea72f3dbca836341670

chore: Update to latest mono

---

src/Uno.Wasm.Bootstrap/Packager/packager.cs

The linker was not emitting the symbols from the linker-in path.
Fixes https://github.com/unoplatform/uno/issues/3150
An updated is posted in mono for the packager: https://github.com/mono/mono/pull/19863

fix(debugger): Fix using bitcode files breaks the debugger

---

src/Uno.Wasm.Bootstrap/ShellTask.cs

The instructions were incorrectly mentioning the Windows command prompt, instead of the WSL shell.

fix: Adjust WSL mono install script instructions

---

src/Uno.Wasm.Bootstrap/ShellTask.cs

Fixes errors such as :
```
System.IO.FileLoadException: Could not load file or assembly 'System.Numerics.Vectors, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
```

fix: Remove span dependency for ShellTask

---

src/Uno.Wasm.Bootstrap/ShellTask.cs

fixes https://github.com/unoplatform/Uno.Wasm.Bootstrap/issues/377#L528

fix: Invalid path for bash in wsl on 64bits conditions

---

src/Uno.Wasm.Bootstrap/Constants.cs
src/Uno.Wasm.Bootstrap/ShellTask.cs

- Revert to previous runtime
- Fix emscripten for windows not disabled properly with `WasmShellEnableEmscriptenWindows`

Misc fixes

---

src/Uno.Wasm.Bootstrap/ShellTask.cs
src/Uno.Wasm.Packager/packager.cs

Restores linker original behavior of keeping parameter names even if unused. This can break reflection based algorithms in very subtle ways (MonacoEditor is one)

fix: Restore metadata for parameter names

---

src/Uno.Wasm.Bootstrap/build/Uno.Wasm.Bootstrap.Publish.targets
src/Uno.Wasm.Bootstrap/build/Uno.Wasm.Bootstrap.targets

Command like `dotnet build -o c:\Temp\wasm\` produced error `error : System.IO.IOException: The filename, directory name, or volume label syntax is incorrect. : '\\?\c:\Temp\wasm\/dist\package_50d3e66f6ede02ff1eb699943f97d000fa3256fd'`
Fixed

Fixed incorrect output path concatenation when cusom output path is provided

---

src/Uno.Wasm.Packager/packager.cs

The `-emit-llvm` emscripten parameters makes a small app build time go from 105s to 92s.

feat: Add `-emit-llvm` flag to improve AOT build performance

---

src/Uno.Wasm.Packager/packager.cs

This option seems to be impacting the memory usage significantly

fix: Disable `-emit-llvm`, remove unused options

---

src/Uno.Wasm.Bootstrap/WasmScripts/uno-bootstrap.js

This change avoids having double downloads while the main app initializes and benefit from the already cached content.

perf: Move offline service worker initialization after app init

---

src/Uno.Wasm.Bootstrap/Constants.cs
src/Uno.Wasm.StaticLinking.Aot.UITests/package.json
src/WasmAot.UITests/package.json

This update fixes AOT compilation missing filter-clauses fallback to interpreter.

fix: Update runtime to latest

---

src/Uno.Wasm.Packager/packager.cs

Debugger logging is useful to debug the debugger, an unlikely scenario for common cases.

fix: Disable debugger logging

---

src/Uno.Wasm.Bootstrap-netcore-only.slnf
src/Uno.Wasm.Bootstrap/build/Uno.Wasm.Bootstrap.targets
src/Uno.Wasm.Sample/sample.common.props

net6.0 removes content from the `Content` item group, and moves them to `StaticWebAsset`, which is now added in the Asset parameter of ShellTask.

fix(net6): Ensure wwwroot folder is included in the dist output

---

src/Uno.Wasm.Bootstrap/Constants.cs

Related to https://github.com/unoplatform/uno/discussions/7999

fix: Update runtime to allow for debugger host to run without net5 installed

---

src/Uno.Wasm.Bootstrap/build/Uno.Wasm.Bootstrap.targets
src/Uno.Wasm.Bootstrap/ts/Uno/WebAssembly/AotProfilerSupport.ts
src/Uno.Wasm.Bootstrap/ts/Uno/WebAssembly/Bootstrapper.ts
src/Uno.Wasm.Bootstrap/ts/types/dotnet/index.d.ts

- fixes the generation of the AOT profile under net7
- Add the ability to disable the automatic inclusion of Microsoft.Windows.Compatibility (https://github.com/unoplatform/Uno.Wasm.Bootstrap/issues/423)

AOT Profiler fixes

---

src/Uno.Wasm.Bootstrap/build/Uno.Wasm.Bootstrap.targets

```
/__w/1/s/.nuget/uno.wasm.bootstrap/4.0.0-dev.191/build/Uno.Wasm.Bootstrap.targets(162,5): error MSB4216: Could not run the "UnoInstallSDKTask_v504004051c4437becf061c14ff3f5d3f49cd00b7" task because MSBuild could not create or connect to a task host with runtime "CLR4" and architecture "x64".  Please ensure that (1) the requested runtime and/or architecture are available on the machine, and (2) that the required executable "/__t/dotnet/sdk/6.0.101/MSBuild.exe" exists and can be run. [/__w/1/s/src/Uno.Playground.WASM/Uno.Playground.WASM.csproj]
```

fix: Remove TaskFactory use as it fails on linux

---

src/Uno.Wasm.Bootstrap/Constants.cs
src/Uno.Wasm.Bootstrap/ShellTask.cs
src/Uno.Wasm.Bootstrap/ts/Uno/WebAssembly/Bootstrapper.ts
src/Uno.Wasm.Bootstrap/ts/Uno/WebAssembly/LogProfilerSupport.ts
src/Uno.Wasm.Bootstrap/ts/types/dotnet/index.d.ts
src/Uno.Wasm.Bootstrap/ts/types/dotnet/mono.d.ts
src/Uno.Wasm.Sample/WasmScripts/test.js
src/Uno.Wasm.SampleNet6.LogProfiler/LinkerConfig.xml
src/Uno.Wasm.SampleNet6.LogProfiler/Uno.Wasm.SampleNet6.LogProfiler.csproj

gzip of the mlpd file is disabled as the latest builds (VS 17.4) of the xamarin profiler do not seem to support it properly.

fix: Restore log profiler feature

---

doc/using-the-bootstrapper.md

The section title for "Bootstrapper versions and .NET runtimes" had a "m" where the "n" should have been in the word "versions".

Fixed Typo in Section Title

---

src/Uno.Wasm.Bootstrap/WasmScripts/service-worker.js
src/Uno.Wasm.Bootstrap/ts/Uno/WebAssembly/Bootstrapper.ts

Instead of `eval`ing the `uno-config.js` file, `service-worker.js` is now loaded as a module to allow `import`ing the `uno-config.js` module.
Should fix #624.

fix: Fixed service worker install error

---

doc/deploy-and-publish.md

#691
Updated the text of the docs to Windows 10/11 and changed the Windows Store to Microsoft Store with a new link, because the old one currently takes you to a page where it is not easy to find the desired item. 
https://www.microsoft.com/en-us/search/result.aspx?q=ubuntu
https://apps.microsoft.com/store/search/ubuntu

docs: update text and link to Microsoft Store

---

src/Uno.Wasm.Bootstrap/WasmCSS/uno-bootstrap.css
src/Uno.Wasm.Bootstrap/ts/Uno/WebAssembly/Bootstrapper.ts

This change undoes the Persistent background changes made in https://github.com/unoplatform/Uno.Wasm.Bootstrap/pull/692, because it turns out they are not the crux of the problem.
When the WASM app loads, after the bootstrapper is done, it currently removes the loader (`.uno-loader`) and then the app itself is initialized. This takes a few hundreds of milliseconds after which Uno itself creates its own "loader" (`#uno-loading`). Unfortunately, those milliseconds are a problem - as they mean that a plain white background will flash there which is very jarring.
This PR changes the default behavior of the bootstrapper to keep the `.uno-loader` in place even after initialization is done until some child is actually added to `uno-body`. This means that it will stay displayed while the actual …

feat!(?): Do not remove loader unless explicitly required

---

src/Uno.Wasm.Bootstrap/ts/Uno/WebAssembly/Bootstrapper.ts

Currently there are two splash screens - one in Bootstrapper and one in Uno. This change will allow the Uno app to indicate the bootstrapper should avoid removing its splash screen, and let this concern for the Uno app to handle. This will ensure there will be absolutely no flashing of blank page before the app loads.
The change is done in a way that there will be nothing breaking - e.g. new bootstrapper will still work with older versions of Uno and new Uno versions will still work with older versions of bootstrapper.
This commit and PR https://github.com/unoplatform/uno/pull/11864 in Uno will add support for this feature - https://github.com/unoplatform/uno/pull/11864/commits/39d44ee3fa99cccb00e73ea3df354e1e81c0e989

feat: Allow Uno app to persist the loader

---

src/Uno.Wasm.Bootstrap/WasmCSS/uno-bootstrap.css

fixes https://github.com/unoplatform/Uno.Wasm.Bootstrap/issues/706
The changes are made to match the styling in Uno.UI

fix: Adjust splash screen image sizing

---

src/Uno.Wasm.Bootstrap/ShellTask.cs
src/Uno.Wasm.Bootstrap/Uno.Wasm.Bootstrap.csproj
src/Uno.Wasm.Bootstrap/UnoInstallSDKTask.cs
src/Uno.Wasm.Bootstrap/build/Uno.Wasm.Bootstrap.targets
src/Uno.Wasm.Packager/packager.cs

This avoids transient issues when upgrading the bootstrapper on the same runtime folder, while having tuner changes.
Fixes https://github.com/unoplatform/Uno.Wasm.Bootstrap/issues/717

fix(tuner): Don't copy the tuner binaries in the runtime tools folder

---

src/Directory.Build.props
src/Uno.Wasm.Bootstrap/build/Uno.Wasm.Bootstrap.props

fixes https://github.com/unoplatform/Uno.Wasm.Bootstrap/issues/782

fix: Opt out of VS build acceleration

---

src/Uno.Wasm.Bootstrap/ShellTask.cs

fix: remove double slash in the path of uno-config.js

---

src/Uno.Wasm.Bootstrap/WasmScripts/service-worker.js

See https://developercommunity.visualstudio.com/t/BrowserLink-WebSocket-is-disconnecting-a/10500228

fix: Disable service worker in debug to work around service workers interfering with browserlink

---

.vsts-ci-windows-tests.yml
src/Uno.Wasm.Bootstrap/Extensions/PathHelper.cs
src/Uno.Wasm.Bootstrap/RemoveDirTask.cs
src/Uno.Wasm.Bootstrap/ShellTask.cs
src/Uno.Wasm.Bootstrap/build/Uno.Wasm.Bootstrap.targets

Related to https://github.com/unoplatform/Uno.Wasm.Bootstrap/pull/814

fix: Remove readonly attribute for output path deletion

---

src/Uno.Wasm.Bootstrap/build/Uno.Wasm.Bootstrap.props

This allows for VS to avoid showing "reload project" as caps get defined when nuget packages are restored

fix: Don't define caps when the uno.sdk is present

---

doc/linker-configuration.md

I found a dead link and I added some Info about the already existing `LinkerConfig.xml` in WASM-projects.

[doc] Correct link and add info about existing `Linkerconfig.xml` on WASM

---

build/ci/stage-build-windows-tests.yml
src/Uno.Wasm.Bootstrap/StaticWebAssetsResolverTask.cs

Fixes #854, fixes https://github.com/unoplatform/uno/issues/16892
I'm not sure if this is the right approach, but it feels reasonable?

feat: Support new Fingerprint and Integrity metadata required in .NET 9 SDK Preview 4

---

src/Uno.Wasm.Bootstrap/ShellTask.cs
src/Uno.Wasm.Packager/CapturingAssemblyResolver.cs
src/Uno.Wasm.Packager/packager.cs

This change ensures that assemblies are used first by the compilation referenced assemblies, then by search paths if not available.

fix: Use assembly full path search first

---

src/Uno.Wasm.Bootstrap/ts/Uno/WebAssembly/Bootstrapper.ts

passing `{credentials: "same-origin"}` into `fetch()` calls made by `Bootstrapper.ts` (`uno-bootstrap.js`in eventual web publish) means that the Uno Platform Wasm App will work on web hosting where we are behind authentication, requiring access to an authentication cookie (such as Azure Static Web Apps 'Password Protection')
addresses, fixes #875

fix: pass same-origin credentials - fixes #875

---

doc/toc.yml

Adjusted the name of Deep linking in toc.yml to include the more common routing for web dev.

chore: Update DeepLinking in toc.yml

---

src/Uno.Wasm.Bootstrap/build/Uno.Wasm.Bootstrap.targets

Fixes a msbuild task dependencies breaking change introduced in .NET SDK 9.0.102.

fix: Ensure explicit dependency for manifest generation

---

doc/features-module-linking.md
src/Uno.Wasm.Bootstrap/build/Uno.Wasm.Bootstrap.targets
src/Uno.Wasm.StaticLinking.Shared/Common.props

This avoids the use of Content as the source, which may cause duplicates in recent builds in .NET automatic assets management.

feat: Add support for WasmShellNativeFileReference

---

src/Uno.Wasm.Bootstrap/ts/Uno/WebAssembly/Bootstrapper.ts

When the user adjusts the HTML to not include the `<img>` in loader, the code that tries to set the attribute on it fails with null ref
Fixes https://github.com/unoplatform/Uno.Wasm.Bootstrap/issues/963

fix: Do not crash in case of a customized loader

---

src/Uno.Wasm.Bootstrap.Server/build/Uno.Wasm.Bootstrap.Server.targets
src/Uno.Wasm.Bootstrap/build/Uno.Wasm.Bootstrap.targets

**GitHub Issue:** closes https://github.com/unoplatform/Uno.Wasm.Bootstrap/issues/973
The previous fix (https://github.com/unoplatform/Uno.Wasm.Bootstrap/pull/974) was assuming that `_CachedBuildStaticWebAssetItems` were ambiently provided to the server project, but it may happen that `_CachedBuildStaticWebAssetItems` is not always populated.
This change moves from using `_CachedBuildStaticWebAssetItems` before it's generated by `GetCurrentProjectBuildStaticWebAssetItems` to after it's been generated. This is done by changing the targets of the msbuild invocation in `ResolveReferencedProjectsStaticWebAssets` so that it uses our target as the invocation output, instead of the original one.

fix: Adjust workaround for #973
